name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  unit:
    name: Unit Test
    runs-on: windows-latest
    strategy:
      matrix:
        php-version: [7.3, 7.4, 8.0, 8.1]
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
        env:
          phpts: ts
      - name: Composer Install
        run: |
          rm composer.lock
          composer install
      - name: Test PHP ${{ matrix.php-version }}
        run: |
          cp phpunit.dist.xml phpunit.xml
          .\vendor\bin\phpunit
